# fly.toml app configuration file generated for gre-flash-cards on 2026-08-05T15:26:04+05:45
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gre-flash-cards'
primary_region = 'ams'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpus = 1
  memory_mb = 256

[mounts]
  source = "vocab_data"
  destination = "/app/data"

[build]